import { Product } from "./types";

export const products: Product[] = [
    // Pipes Images
    {
        id: 1,
        title: "Pipe Pak-Arab 1/2inch",
        image: ["/pipe/pipe2.png"],
        products: "pipe-pak-arab-one",
        price: 650,
        discount: 10,
        category: "pipe",
        description: "Pak-Arab is Best Quality Product Pipe.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // Coil Featured
    {
        id: 2,
        title: "Coil 3.29",
        image: ["/coil/coils7.jpg"],
        products: "coil-one",
        price: 6000,
        discount: 25,
        category: "coil",
        description: "Coil the best quality in the product.",
        size:["Coil 3.29"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // Elbow Featured
    {
        id: 3,
        title: "Elbow 1/2inch",
        image: ["/elbow/elb1.jpg"],
        products: "elbow-one",
        price: 40,
        discount: 20,
        category: "fitting",
        description: "Elbow is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // China Sheet Featured
    {
        id: 4,
        title: "Metal Grey Long 8+2",
        image: ["/sheet/china8.jpg"],
        products: "sheet-one",
        price: 850,
        discount: 20,
        category: "sheet",
        description: "Metal Long Grey the best quality in the product.",
        size:["8+2"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // Double Bib Cock Featured
    {
        id: 5,
        title: "Double Bib Cock",
        image: ["/cock/bib4.jpg"],
        products: "bib-cock-one",
        price: 800,
        discount: 30,
        category: "bibcock",
        description: "Double Bib Cock is the best quality in the product.",
        size:["Double Bib Cock"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    // Bulb Featured
    {
        id: 6,
        title: "Bulb 5w",
        image: ["/bulb/bulbs4.jpg"],
        products: "bulb-one",
        price: 300,
        discount: 40,
        category: "bulb",
        description: "Bulb 5w the best quality in the product.",
        size:["Bulb 5w"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // Solution Featured
    {
        id: 7,
        title: "CPVC Solution Small",
        image: ["/solution/sol1.jpg"],
        products: "cement-one",
        price: 550,
        discount: 40,
        category: "solution",
        description: "Soltuion E.Z Weld is the best quality in the product",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // Breaker Featured
    {
        id: 8,
        title: "Double Pole Breaker 10amp",
        image: ["/breaker/brek14.png"],
        products: "breaker-one",
        price: 900,
        discount: 30,
        category: "breaker",
        description: "Double Pole Breaker 10amp the best quality in the product.",
        size:["10amp"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // Pipe 
    {
        id: 9,
        title: "Pipe Pak-Arab 3/4inch",
        image: ["/pipe/pipe1.png"],
        products: "pipe-pak-arab-two",
        price: 850,
        discount: 10,
        category: "pipe",
        description: "Pak-Arab is Best Quality Product Pipe.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#fafafa", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 10,
        title: "Pipe Pak-Arab 1inch",
        image: ["/pipe/pipe8.png"],
        products: "pipe-pak-arab-three",
        price: 1500,
        discount: 10,
        category: "pipe",
        description: "Pak-Arab is Best Quality Product Pipe.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },    
    {
        id: 11,
        title: "Pipe Pak-Arab 1 1/4inch",
        image: ["/pipe/pipe10.jpg"],
        products: "pipe-pak-arab-four",
        price: 2000,
        discount: 15,
        category: "pipe",
        description: "Pak-Arab is Best Quality Product Pipe.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 12,
        title: "Pipe Pak-Arab 1 1/2inch",
        image: ["/pipe/pipe16.jpg"],
        products: "pipe-pak-arab-five",
        price: 2500,
        discount: 20,
        category: "pipe",
        description: "Pak-Arab is Best Quality Product Pipe.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 13,
        title: "Pipe Pak-Arab 2inch",
        image: ["/pipe/pipe15.jpg"],
        products: "pipe-pak-arab-six",
        price: 2800,
        discount: 20,
        category: "pipe",
        description: "Pak-Arab is Best Quality Product Pipe.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 14,
        title: "Pipe Pak-Arab 3inch",
        image: ["/pipe/pipe13.jpg"],
        products: "pipe-pak-arab-seven",
        price: 3000,
        discount: 20,
        category: "pipe",
        description: "Pak-Arab is Best Quality Product Pipe.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 15,
        title: "Pipe Pak-Arab 4inch",
        image: ["/pipe/pipe14.jpg"],
        products: "pipe-pak-arab-eight",
        price: 3500,
        discount: 20,
        category: "pipe",
        description: "Pak-Arab is Best Quality Product Pipe.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 16,
        title: "Pipe Pak-Arab 5inch",
        image: ["/pipe/pipe17.jpg"],
        products: "pipe-pak-arab-nine",
        price: 4000,
        discount: 20,
        category: "pipe",
        description: "Pak-Arab is Best Quality Product Pipe.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 17,
        title: "Pipe Pak-Arab 6inch",
        image: ["/pipe/pipe6.png"],
        products: "pipe-pak-arab-ten",
        price: 5500,
        discount: 20,
        category: "pipe",
        description: "Pak-Arab is Best Quality Product Pipe.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 18,
        title: "Pipe Pak-Arab 8inch",
        image: ["/pipe/pipe7.png"],
        products: "pipe-pak-arab-eleven",
        price: 8000,
        discount: 30,
        category: "pipe",
        description: "Pak-Arab is Best Quality Product Pipe.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 19,
        title: "Pipe Pak-Arab 10inch",
        image: ["/pipe/pipe18.jpg"],
        products: "pipe-pak-arab-twelve",
        price: 10000,
        discount: 30,
        category: "pipe",
        description: "Pak-Arab is Best Quality Product Pipe.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // Elbow 
    {
        id: 20,
        title: "Elbow 3/4inch",
        image: ["/elbow/elb1.jpg"],
        products: "elbow-two",
        price: 50,
        discount: 30,
        category: "fitting",
        description: "Elbow is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 21,
        title: "Elbow 1inch",
        image: ["/elbow/elb1.jpg"],
        products: "elbow-three",
        price: 60,
        discount: 30,
        category: "fitting",
        description: "Elbow is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 22,
        title: "Elbow 1 1/4inch",
        image: ["/elbow/elb1.jpg"],
        products: "elbow-four",
        price: 90,
        discount: 30,
        category: "fitting",
        description: "Elbow is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 23,
        title: "Elbow 1 1/2inch",
        image: ["/elbow/elb1.jpg"],
        products: "elbow-five",
        price: 120,
        discount: 40,
        category: "fitting",
        description: "Elbow is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 24,
        title: "Elbow 2inch",
        image: ["/elbow/elb1.jpg"],
        products: "elbow-six",
        price: 150,
        discount: 40,
        category: "fitting",
        description: "Elbow is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 25,
        title: "Elbow 3inch",
        image: ["/elbow/elb1.jpg"],
        products: "elbow-seven",
        price: 250,
        discount: 40,
        category: "fitting",
        description: "Elbow is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 26,
        title: "Elbow 4inch",
        image: ["/elbow/elb1.jpg"],
        products: "elbow-eight",
        price: 350,
        discount: 40,
        category: "fitting",
        description: "Elbow is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 27,
        title: "Elbow 5inch",
        image: ["/elbow/elb1.jpg"],
        products: "elbow-nine",
        price: 1000,
        discount: 50,
        category: "fitting",
        description: "Elbow is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 28,
        title: "Elbow 6inch",
        image: ["/elbow/elb1.jpg"],
        products: "elbow-ten",
        price: 1500,
        discount: 50,
        category: "fitting",
        description: "Elbow is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 29,
        title: "Elbow 8inch",
        image: ["/elbow/elb1.jpg"],
        products: "elbow-eleven",
        price: 2000,
        discount: 50,
        category: "fitting",
        description: "Elbow is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 30,
        title: "Elbow 10inch",
        image: ["/elbow/elb1.jpg"],
        products: "elbow-twelve",
        price: 2500,
        discount: 50,
        category: "fitting",
        description: "Elbow is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // 45 Degree
    {
        id: 31,
        title: "45 1/2inch",
        image: ["/45/deg2.jpg"],
        products: "degree-one",
        price: 50,
        discount: 30,
        category: "fitting",
        description: "45 degree is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 32,
        title: "45 3/4inch",
        image: ["/45/deg2.jpg"],
        products: "degree-two",
        price: 60,
        discount: 30,
        category: "fitting",
        description: "45 degree is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 33,
        title: "45 1inch",
        image: ["/45/deg2.jpg"],
        products: "degree-three",
        price: 70,
        discount: 30,
        category: "fitting",
        description: "45 degree is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 34,
        title: "45 1 1/4 4inch",
        image: ["/45/deg2.jpg"],
        products: "degree-four",
        price: 100,
        discount: 40,
        category: "fitting",
        description: "45 degree is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 35,
        title: "45 1 1/2inch",
        image: ["/45/deg2.jpg"],
        products: "degree-five",
        price: 100,
        discount: 0,
        category: "fitting",
        description: "45 degree is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 36,
        title: "45 2inch",
        image: ["/45/deg2.jpg"],
        products: "degree-six",
        price: 120,
        discount: 0,
        category: "fitting",
        description: "45 degree is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 37,
        title: "45 3inch",
        image: ["/45/deg2.jpg"],
        products: "degree-seven",
        price: 250,
        discount: 40,
        category: "fitting",
        description: "45 degree is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 38,
        title: "45 4inch",
        image: ["/45/deg2.jpg"],
        products: "degree-eight",
        price: 350,
        discount: 40,
        category: "fitting",
        description: "45 degree is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 39,
        title: "45 5inch",
        image: ["/45/deg2.jpg"],
        products: "degree-nine",
        price: 700,
        discount: 40,
        category: "fitting",
        description: "45 degree is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 40,
        title: "45 6inch",
        image: ["/45/deg2.jpg"],
        products: "degree-ten",
        price: 1000,
        discount: 40,
        category: "fitting",
        description: "45 degree is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 41,
        title: "45 8inch",
        image: ["/45/deg2.jpg"],
        products: "degree-eleven",
        price: 1800,
        discount: 50,
        category: "fitting",
        description: "45 degree is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 42,
        title: "45 10inch",
        image: ["/45/deg2.jpg"],
        products: "degree-twelve",
        price: 2500,
        discount: 50,
        category: "fitting",
        description: "45 degree is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // Tee
    {
        id: 43,
        title: "Tee 1/2inch",
        image: ["/tee/t6.jpg"],
        products: "tee-one",
        price: 40,
        discount: 20,
        category: "fitting",
        description: "Tee is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 44,
        title: "Tee 3/4inch",
        image: ["/tee/t6.jpg"],
        products: "tee-two",
        price: 50,
        discount: 20,
        category: "fitting",
        description: "Tee is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 45,
        title: "Tee 1inch",
        image: ["/tee/t6.jpg"],
        products: "tee-three",
        price: 60,
        discount: 20,
        category: "fitting",
        description: "Tee is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 46,
        title: "Tee 1 1/4inch",
        image: ["/tee/t6.jpg"],
        products: "tee-four",
        price: 80,
        discount: 20,
        category: "fitting",
        description: "Tee is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },        
    {
        id: 47,
        title: "Tee 1 1/2inch",
        image: ["/tee/t6.jpg"],
        products: "tee-five",
        price: 80,
        discount: 0,
        category: "fitting",
        description: "Tee is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },     
    {
        id: 48,
        title: "Tee 2inch",
        image: ["/tee/t6.jpg"],
        products: "tee-six",
        price: 120,
        discount: 0,
        category: "fitting",
        description: "Tee is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 49,
        title: "Tee 3inch",
        image: ["/tee/t6.jpg"],
        products: "tee-seven",
        price: 250,
        discount: 30,
        category: "fitting",
        description: "Tee is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 50,
        title: "Tee 4inch",
        image: ["/tee/t6.jpg"],
        products: "tee-eight",
        price: 350,
        discount: 30,
        category: "fitting",
        description: "Tee is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 51,
        title: "Tee 5inch",
        image: ["/tee/t6.jpg"],
        products: "tee-nine",
        price: 800,
        discount: 40,
        category: "fitting",
        description: "Tee is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 52,
        title: "Tee 6inch",
        image: ["/tee/t6.jpg"],
        products: "tee-ten",
        price: 1000,
        discount: 40,
        category: "fitting",
        description: "Tee is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 53,
        title: "Tee 8inch",
        image: ["/tee/t6.jpg"],
        products: "tee-eleven",
        price: 1500,
        discount: 40,
        category: "fitting",
        description: "Tee is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 54,
        title: "Tee 10inch",
        image: ["/tee/t6.jpg"],
        products: "tee-twelve",
        price: 2000,
        discount: 40,
        category: "fitting",
        description: "Tee is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    // Socket
    {
        id: 55,
        title: "Socket 1/2inch",
        image: ["/socket/soc2.jpg"],
        products: "socket-one",
        price: 15,
        discount: 0,
        category: "fitting",
        description: "Socket is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 56,
        title: "Socket 3/4inch",
        image: ["/socket/soc2.jpg"],
        products: "socket-two",
        price: 20,
        discount: 0,
        category: "fitting",
        description: "Socket is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 57,
        title: "Socket 1inch",
        image: ["/socket/soc2.jpg"],
        products: "socket-three",
        price: 40,
        discount: 0,
        category: "fitting",
        description: "Socket is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 58,
        title: "Socket 1 1/4inch",
        image: ["/socket/soc2.jpg"],
        products: "socket-four",
        price: 60,
        discount: 0,
        category: "fitting",
        description: "Socket is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 59,
        title: "Socket 1 1/2inch",
        image: ["/socket/soc2.jpg"],
        products: "socket-five",
        price: 120,
        discount: 20,
        category: "fitting",
        description: "Socket is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 60,
        title: "Socket 2inch",
        image: ["/socket/soc2.jpg"],
        products: "socket-six",
        price: 150,
        discount: 20,
        category: "fitting",
        description: "Socket is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 61,
        title: "Socket 3inch",
        image: ["/socket/soc2.jpg"],
        products: "socket-seven",
        price: 180,
        discount: 20,
        category: "fitting",
        description: "Socket is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 62,
        title: "Socket 4inch",
        image: ["/socket/soc2.jpg"],
        products: "socket-eight",
        price: 220,
        discount: 20,
        category: "fitting",
        description: "Socket is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 63,
        title: "Socket 5inch",
        image: ["/socket/soc2.jpg"],
        products: "socket-nine",
        price: 500,
        discount: 30,
        category: "fitting",
        description: "Socket is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 64,
        title: "Socket 6inch",
        image: ["/socket/soc2.jpg"],
        products: "socket-ten",
        price: 600,
        discount: 20,
        category: "fitting",
        description: "Socket is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 65,
        title: "Socket 8inch",
        image: ["/socket/soc2.jpg"],
        products: "socket-eleven",
        price: 1200,
        discount: 40,
        category: "fitting",
        description: "Socket is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 66,
        title: "Socket 10inch",
        image: ["/socket/soc2.jpg"],
        products: "socket-twelve",
        price: 1500,
        discount: 40,
        category: "fitting",
        description: "Socket is the best quality in the product.",
        size:["1/2", "3/4", "1", "1 1/4", "1 1/2", "2", "3", "4", "5", "6", "8", "10"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    // Bib Cock
    {
        id: 67,
        title: "Bib Cock",
        image: ["/cock/bib7.png"],
        products: "bib-cock-two",
        price: 350,
        discount: 30,
        category: "bibcock",
        description: " Bib Cock is the best quality in the product.",
        size:["Bib Cock"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    }, 
    {
        id: 69,
        title: "Tee Cock",
        image: ["/cock/bib1.jpg"],
        products: "bib-cock-three",
        price: 350,
        discount: 30,
        category: "bibcock",
        description: "Tee Cock is the best quality in the product.",
        size:["Tee Cock"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 70,
        title: "Besan Bib Cock",
        image: ["/cock/bib2.jpg"],
        products: "bib-cock-four",
        price: 1000,
        discount: 50,
        category: "bibcock",
        description: "Besan Bib Cock is the best quality in the product.",
        size:["Besan Bib Cock"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // Solution
    {
        id: 71,
        title: "CPVC Solution 75ml",
        image: ["/solution/sol1.jpg"],
        products: "cement-two",
        price: 750,
        discount: 40,
        category: "solution",
        description: "Soltuion E.Z Weld is the best quality in the product.",
        size:["Soltion 75ml"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 72,
        title: "CPVC Solution 118ml",
        image: ["/solution/sol1.jpg"],
        products: "cement-three",
        price: 1000,
        discount: 20,
        category: "solution",
        description: "Soltuion E.Z Weld is the best quality in the product.",
        size:["Solution 118ml"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 73,
        title: "CPVC Solution 240ml",
        image: ["/solution/sol1.jpg"],
        products: "cement-four",
        price: 2000,
        discount: 30,
        category: "solution",
        description: "Soltuion E.Z Weld is the best quality in the product.",
        size:["Solution 240ml"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // coil
    {
        id: 74,
        title: "Coil 7.29",
        image: ["/coil/coils6.jpg"],
        products: "coil-two",
        price: 14000,
        discount: 30,
        category: "coil",
        description: "Coil the best quality in the product.",
        size:["Coil 7.29"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 75,
        title: "Coil 7.36",
        image: ["/coil/coils6.jpg"],
        products: "coil-three",
        price: 20000,
        discount: 30,
        category: "coil",
        description: "Coil the best quality in the product.",
        size:["Coil 7.36"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 76,
        title: "Coil 7.44",
        image: ["/coil/coils7.jpg"],
        products: "coil-four",
        price: 25000,
        discount: 20,
        category: "coil",
        description: "Coil the best quality in the product.",
        size:["Coil 7.44"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // China Sheet
    {
        id: 77,
        title: "Metal Grey Long 6+2",
        image: ["/sheet/china8.jpg"],
        products: "sheet-two",
        price: 800,
        discount: 20,
        category: "sheet",
        description: "Metal Long Grey the best quality in the product.",
        size:["6+2",],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 78,
        title: "Metal Grey Long 4+2",
        image: ["/sheet/china8.jpg"],
        products: "sheet-three",
        price: 700,
        discount: 20,
        category: "sheet",
        description: "Metal Long Grey the best quality in the product.",
        size:["4+2",],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 79,
        title: "Metal Grey Long 2+2",
        image: ["/sheet/china8.jpg"],
        products: "sheet-four",
        price: 400,
        discount: 20,
        category: "sheet",
        description: "Metal Long Grey the best quality in the product.",
        size:["2+2",],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 80,
        title: "Metal White Long 8+2",
        image: ["/sheet/china5.jpg"],
        products: "sheet-five",
        price: 850,
        discount: 20,
        category: "sheet",
        description: "Metal Long White the best quality in the product.",
        size:["8+2", ],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 81,
        title: "Metal White Long 6+2",
        image: ["/sheet/china5.jpg"],
        products: "sheet-six",
        price: 800,
        discount: 20,
        category: "sheet",
        description: "Metal Long White the best quality in the product.",
        size:["6+2",],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 82,
        title: "Metal White Long 4+2",
        image: ["/sheet/china5.jpg"],
        products: "sheet-seven",
        price: 700,
        discount: 20,
        category: "sheet",
        description: "Metal Long White the best quality in the product.",
        size:["4+2",],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 83,
        title: "Metal White Long 2+2",
        image: ["/sheet/china5.jpg"],
        products: "sheet-eight",
        price: 400,
        discount: 20,
        category: "sheet",
        description: "Metal Long White the best quality in the product.",
        size:["2+2"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 84,
        title: "Metal Brown 8+2",
        image: ["/sheet/china9.jpg"],
        products: "sheet-nine",
        price: 800,
        discount: 30,
        category: "sheet",
        description: "Metal Brown the best quality in the product.",
        size:["8+2"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 85,
        title: "Metal Brown 6+2",
        image: ["/sheet/china9.jpg"],
        products: "sheet-ten",
        price: 700,
        discount: 30,
        category: "sheet",
        description: "Metal Brown the best quality in the product.",
        size:["6+2"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 86,
        title: "Metal Brown 4+2",
        image: ["/sheet/china9.jpg"],
        products: "sheet-eleven",
        price: 650,
        discount: 30,
        category: "sheet",
        description: "Metal Brown the best quality in the product.",
        size:["4+2"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 87,
        title: "Metal Brown 2+2",
        image: ["/sheet/china9.jpg"],
        products: "sheet-twelve",
        price: 430,
        discount: 30,
        category: "sheet",
        description: "Metal Brown the best quality in the product.",
        size:["2+2"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 88,
        title: "Metal Golden 8+2",
        image: ["/sheet/china4.jpg"],
        products: "sheet-thirteen",
        price: 800,
        discount: 30,
        category: "sheet",
        description: "Metal Golden the best quality in the product.",
        size:["8+2"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 89,
        title: "Metal Golden 6+2",
        image: ["/sheet/china4.jpg"],
        products: "sheet-fourteen",
        price: 700,
        discount: 30,
        category: "sheet",
        description: "Metal Golden the best quality in the product.",
        size:["6+2"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 90,
        title: "Metal Golden 4+2",
        image: ["/sheet/china4.jpg"],
        products: "sheet-fifteen",
        price: 650,
        discount: 30,
        category: "sheet",
        description: "Metal Golden the best quality in the product.",
        size:["4+2"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 91,
        title: "Metal Golden 2+2",
        image: ["/sheet/china4.jpg"],
        products: "sheet-sixteen",
        price: 430,
        discount: 30,
        category: "sheet",
        description: "Metal Golden the best quality in the product.",
        size:["2+2"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // Bubls
    {
        id: 92,
        title: "Bulb 7w",
        image: ["/bulb/bulbs4.jpg"],
        products: "bulb-two",
        price: 350,
        discount: 40,
        category: "bulb",
        description: "Bulb 7w the best quality in the product.",
        size:["7w"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 93,
        title: "Bulb 12w",
        image: ["/bulb/bulbs4.jpg"],
        products: "bulb-three",
        price: 400,
        discount: 40,
        category: "bulb",
        description: "Bulb 12w the best quality in the product.",
        size:["12w"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 94,
        title: "Bulb 18w",
        image: ["/bulb/bulbs4.jpg"],
        products: "bulb-four",
        price: 550,
        discount: 40,
        category: "bulb",
        description: "Bulb 18w the best quality in the product.",
        size:["18w"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    // Breakers
    {
        id: 95,
        title: "Double Pole Breaker 20amp",
        image: ["/breaker/brek14.png"],
        products: "breaker-two",
        price: 950,
        discount: 30,
        category: "breaker",
        description: "Double Pole Breaker 20amp the best quality in the product.",
        size:["20amp"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 96,
        title: "Double Pole Breaker 32amp",
        image: ["/breaker/brek14.png"],
        products: "breaker-three",
        price: 1000,
        discount: 30,
        category: "breaker",
        description: "Double Pole Breaker 32amp the best quality in the product.",
        size:["32amp"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 97,
        title: "Double Pole Breaker 63amp",
        image: ["/breaker/brek14.png"],
        products: "breaker-four",
        price: 1100,
        discount: 30,
        category: "breaker",
        description: "Double Pole Breaker 63amp the best quality in the product.",
        size:["63amp"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 98,
        title: "Single Pole Breaker 10amp",
        image: ["/breaker/brek3.jpg"],
        products: "breaker-five",
        price: 500,
        discount: 30,
        category: "breaker",
        description: "Single Pole Breaker 10amp the best quality in the product.",
        size:["10amp"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 99,
        title: "Single Pole 20amp",
        image: ["/breaker/brek3.jpg"],
        products: "breaker-six",
        price: 550,
        discount: 30,
        category: "breaker",
        description: "Single Pole Breaker 20amp the best quality in the product.",
        size:["20amp"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 100,
        title: "Single Pole 32amp",
        image: ["/breaker/brek3.jpg"],
        products: "breaker-seven",
        price: 600,
        discount: 30,
        category: "breaker",
        description: "Single Pole Breaker 32amp the best quality in the product.",
        size:["32amp"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },
    {
        id: 101,
        title: "Single Pole 63amp",
        image: ["/breaker/brek3.jpg"],
        products: "breaker-eight",
        price: 650,
        discount: 30,
        category: "breaker",
        description: "Single Pole Breaker 63amp the best quality in the product.",
        size:["63amp"],
        color: ["#ffffff", "#000000", "#e60000"],
        quantity: 1,
    },

]
